# Generated by Django 4.2.4 on 2023-08-23 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store3', '0003_alter_cart_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='costumer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
