# Generated by Django 4.2.4 on 2023-08-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store3', '0004_alter_costumer_options_remove_costumer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='roduct',
            new_name='product',
        ),
    ]
